//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_tiet_don_hang
    {
        public int id_chi_tiet_don_hang { get; set; }
        public Nullable<int> id_don_hang { get; set; }
        public Nullable<int> id_sp { get; set; }
        public string ten_sp { get; set; }
        public string color { get; set; }
        public string anh_sp { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<int> don_gia { get; set; }
        public Nullable<int> thanh_tien { get; set; }
    
        public virtual Don_hang Don_hang { get; set; }
        public virtual San_pham San_pham { get; set; }
    }
}
