//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho_hang
    {
        public int id_kh { get; set; }
        public Nullable<int> id_sp { get; set; }
        public string ten_sp { get; set; }
        public string ten_hangsx { get; set; }
        public Nullable<System.DateTime> ngay_nhap { get; set; }
        public Nullable<int> so_luong { get; set; }
        public string size { get; set; }
        public string color { get; set; }
        public Nullable<int> gia_nhap { get; set; }
        public Nullable<int> gia_ban { get; set; }
        public Nullable<int> saleOf { get; set; }
        public Nullable<int> id_loai_sp { get; set; }
    
        public virtual Phan_loai_sp Phan_loai_sp { get; set; }
        public virtual San_pham San_pham { get; set; }
    }
}
