//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoi_dung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nguoi_dung()
        {
            this.Tich_diem = new HashSet<Tich_diem>();
        }
    
        public int id_user { get; set; }
        public string tai_khoan { get; set; }
        public string mat_khau { get; set; }
        public string ho_ten { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string so_dien_thoai { get; set; }
        public string dia_chi { get; set; }
        public string email { get; set; }
        public Nullable<int> id_quyen { get; set; }
    
        public virtual Phan_quyen Phan_quyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tich_diem> Tich_diem { get; set; }
    }
}
