//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SneakerThriffEntities : DbContext
    {
        public SneakerThriffEntities()
            : base("name=SneakerThriffEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chi_tiet_don_hang> Chi_tiet_don_hang { get; set; }
        public virtual DbSet<Don_hang> Don_hang { get; set; }
        public virtual DbSet<Hang_sx> Hang_sx { get; set; }
        public virtual DbSet<Kho_hang> Kho_hang { get; set; }
        public virtual DbSet<Nguoi_dung> Nguoi_dung { get; set; }
        public virtual DbSet<Phan_loai_sp> Phan_loai_sp { get; set; }
        public virtual DbSet<Phan_quyen> Phan_quyen { get; set; }
        public virtual DbSet<San_pham> San_pham { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tich_diem> Tich_diem { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
    }
}
