//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tich_diem
    {
        public int id_tichdiem { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> diem_tich_luy { get; set; }
    
        public virtual Nguoi_dung Nguoi_dung { get; set; }
    }
}
