//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int id_voucher { get; set; }
        public Nullable<int> id_user { get; set; }
        public string code_voucher { get; set; }
        public Nullable<System.DateTime> han_sd { get; set; }
        public Nullable<int> sale { get; set; }
    }
}
